---
- hosts: k3s
  vars_files:
  - environment_vars.yaml
  vars:
  tasks:
  - name: Shut down
    shell:
      cmd: shutdown
    become: true
    tags: ['never','shutdown']
  roles:
  - { role: common,
      tags: ['never','update','setup'] }
  - { role: storage_management,
      tags: ['never','storage_management'] }
- hosts: controlpi
  environment:
  - KUBECONFIG: /home/pi/.kube/config
  vars_files:
  - environment_vars.yaml
  tasks:
  - name: Install controlpi packages
    apt:
      pkg:
      - mosquitto-clients
    become: true
    tags: ['never','cpinstall']
  roles:
  - { role: mqtt,
      tags: ['never','mqtt'] }
  - { role: influx,
      tags: ['never','influx'] }
  - { role: telegraf,
      tags: ['never','telegraf'] }
  - { role: portainer,
      tags: ['never','portainer'] }
  - { role: jupyter,
      tags: ['never','jupyter'] }
  - { role: craftbeerpi,
      tags: ['never','craftbeerpi'] }
